name: Latest blog post workflow
on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  update-readme-with-blog:
    name: Update this repo's README with the latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pull in rss posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: 'https://www.tinhhuynh.dev/feed.xml'
